// <auto-generated />
using System;
using GestorTareas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorTareas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230808175807_Tareas")]
    partial class Tareas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorTareas.Models.Categorias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GestorTareas.Models.CategoriasTareas", b =>
                {
                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("TareaId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriasId")
                        .HasColumnType("int");

                    b.Property<int?>("TareasId")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId", "TareaId");

                    b.HasIndex("CategoriasId");

                    b.HasIndex("TareasId");

                    b.ToTable("CategoriasTareas");
                });

            modelBuilder.Entity("GestorTareas.Models.Tareas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("GestorTareas.Models.CategoriasTareas", b =>
                {
                    b.HasOne("GestorTareas.Models.Categorias", "Categorias")
                        .WithMany("CategoriasTareas")
                        .HasForeignKey("CategoriasId");

                    b.HasOne("GestorTareas.Models.Tareas", "Tareas")
                        .WithMany("CategoriasTareas")
                        .HasForeignKey("TareasId");

                    b.Navigation("Categorias");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("GestorTareas.Models.Categorias", b =>
                {
                    b.Navigation("CategoriasTareas");
                });

            modelBuilder.Entity("GestorTareas.Models.Tareas", b =>
                {
                    b.Navigation("CategoriasTareas");
                });
#pragma warning restore 612, 618
        }
    }
}
